homepage/urls.py
from django.urls import include, path
from . import views
from django.contrib import admin

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.forms import ModelForm

#Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=255, primary_key=True)

    def __str__(self):
        return self.status

homepage/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from .models import Status
from .forms import StatusForm

# Create your views here.
def index(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()

    form = StatusForm()
    statusList = Status.objects.all()

    return render(request, 'index.html', {'form': form, 'statusList': statusList})

homepage/templates/index.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <title>Story 6</title>

  </head>

  <body>
      <br>
      <h class="font-weight-bold" style="font-size: 5vh; margin-left: 8.7%;">Hello, how are you?</h>
      <form method="post" action="{% url 'homepage:index' %}">
        {% csrf_token %}
        <div style="margin-left: 10px; margin-right: 10px;">
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <input id="submitBtn" type="submit" class="btn btn-secondary" style="margin-left: 8.7%;" value="Add">
        </div>
      </form>

      <br><br>
      <div class="container-fluid">
        <div class="row text-center">
          <div class="col">
            <h class="font-weight-bold" style="font-size: 5vh;">Status list</h>
          </div>
        </div>
      </div>
      <br>
      <table id="statustable" class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          {% for i in statusList %}
            <tr class="table-info">
              <td class="table-info">{{ i.status }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>